sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
- 'node'
script:
  - yarn lint
  - yarn test
after_success:
- bash deploy_docs.sh
deploy:
  provider: npm
  email: technik@propertybase.com
  api_key:
    secure: "Tv4Sff+xUPL43qZO0E1FMbLU9dEuhX4Tf/FcBeS/ASmHhEsdf0MtNjo/LRR+ZxvSlHAEJFJRyZeAtfX6xD7rrvFTNWgMhptTFqcy7OFFFdlxre7yRiVhPm1RKzVVAMQ99eQJOfYkT6mPinIKKbMo3eY2iWqdXx2O3fn79dGASyk7fXZkfjiSVG3QpJTV7DkuzIy1uUXNEUt1vIB/lHBRj0QOjV/h13Gst78uxc2Y4xnbvOLEcniv5yssvG85pIfPvOgDnmlApx7Kmoqt6Bsot9QfrAtu5Q5SR034i7Fm8dgyBBJbuDzzxJ5PX+TPARy+Jz60H4EscTFfWTq5WsMtfUAUSyBsNX0ToV8b+7K7/TZFbexBW8mc22KLgQBAjvgKagYip2/htlE7oBQXmSCJg6AUjoExeJKPykBX8/KCUzk/l8SwOAvH+L3C9NaGwkZQJcftvzDBA7m8FpMklkJhWWvkff33PIXOsuAUyhDxx00Chglu4SC7kpyOBX5xfhOxBUlcG0nCZahITkwAdVN63ut8tXyQ5xghbTyKRE3mkLZ3hdtK7KC0gR6xubxdv1iI8kOhg2Hg6Smxeb/jTXkCpoTBUDBDV0bgs3infEcbEwHTlSwVD9ByoCty+IgXnob2O1conuI0vazwTfyymRJtKZ0appt1uYgkXYXXr5hmJDA="
  on:
    tags: true
    repo: propertybase/react-lds
  skip_cleanup: true
env:
  global:
  - GITHUB_REPO: propertybase/react-lds
