sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  # There's an open bug in Jest which causes all specs to fail.
  # See: https://github.com/facebook/jest/issues/8069
  #
  # Pinning node to this version solves the problem for now.
  - "11.10.1"
script:
  - yarn lint
  - yarn test
after_success:
  - bash deploy_docs.sh
deploy:
  provider: npm
  email: felix@spoet.tel
  api_key:
    secure: "UhS6zdjUpLFsOS5t3TWkgVB8ZZzmbC295TJomfO2wCy92eSurhqvYFp17hIDFXB4R6y9JfcirzPyOp8bFt5mJ0BBFLlKZsqEznmpqZSj8RIv8A0yD6GiRAo2EIbYy/RxXWai0JzHA5CNXU2410SbBudxVB6UFxg3MxWv9qw0tLANt1pTjwr+PtX7Y7mcLkizr6jqg12EGoKDqaYsHE1IibyE6O6BaZxbaBrQdJJlPkHpq5lhDsXMiQZXN61ojmJQ8f5kzjk1shL3mbaolJccesXJbWU3gyDMYmd0SGh5+NSJB4j9vhVD9CbIaiA5b8ER0oamjh2uIEX5ZMQt58/YVmvuwEGLJ0a8/vqz1nHAYehitpQbicDb86X5bSZZWiPF/yL9j76njUPS1UdUjegtGod69iiAoXeam2uI8Io98BTL172t3DrQKF3hzUHtIl+CpHoA5MHkatSgoIZy4bvwfpI5xOjU/T6MBN+pKrtrSoDoH491uSEocOm+NjjOEutajAZBB+9jR7J42yfbeJ3ArRqysDZ9dHL36QVJndaJOy8z0fIdgDloEE55TkJAipJyFbW8a418q2OXwpAigeTQaeYsMExbpXWEF+n8Z71+ubrqRG6mUUzwDOKTbAHZuI+lEFlR15F2iL9RcSCwIAcHLwyVsk9BxwV7x0ul7zXKnmw="
  on:
    tags: true
    repo: react-lds/react-lds
  skip_cleanup: true
env:
  global:
  - GITHUB_REPO: react-lds/react-lds
